### PR TITLE
logging added, more consistant typing.

### PR DESCRIPTION
**Pull request by 4ldas**
original library used non capitalized typing for logging so made everything non capitalized, besides it looked bit ugly. and added logging to this using tracing and tracing subscriber

### CODE REVIEW

**Comment by 4ldas** [comment]
bit spammed commits haha, i keep editing straight from browser

**Review by MrAliSalehi — CHANGES_REQUESTED** [review]
I think "password" should be a little more descriptive , maybe something like " 2F auth"? or something similar
and for the code as well, maybe "verification code" would be better ?

**Review by MrAliSalehi — COMMENTED** [review]
and i think adding extra dep just for tracing is not necessary, since the goal is to be "minimal" 
but this is also a great feature as an "optional" cargo gen flag

**Comment by 4ldas** [comment]
i agree

> and i think adding extra dep just for tracing is not necessary, since the goal is to be "minimal" but this is also a great feature as an "optional" cargo gen flag

i agree with this 

> I think "password" should be a little more descriptive , maybe something like " 2F auth"? or something similar and for the code as well, maybe "verification code" would be better ?

i agree with this

**Comment by 4ldas** [comment]
> and i think adding extra dep just for tracing is not necessary, since the goal is to be "minimal" but this is also a great feature as an "optional" cargo gen flag

i was thinking sort of about it, realistically any medium-large or even small bots could benefit even a little bit from logging, it tells when connecting to server, etc. Up to you to decide i guess

**Comment by 4ldas** [comment]
let me make a commit for the more descriptive inputs

**Review by MrAliSalehi — APPROVED** [review]

**Comment by 4ldas** [comment]
nowdays i realistically try to impliment tracing for everything

**Comment by MrAliSalehi** [comment]
its fine for now, can you do a fmt as well?

**Comment by 4ldas** [comment]
> its fine for now, can you do a fmt as well?

Explain what you mean

**Comment by MrAliSalehi** [comment]
> > its fine for now, can you do a fmt as well?
> 
> Explain what you mean

run cargo fmt to pass the checks, please

**Pull request merged**
